"use client";

import { useState } from "react";
import { useWallet } from "@/components/WalletProvider";
import {
  buildContractCall,
  submitTransaction,
  POOL_CONTRACT_ID,
  queryContract,
} from "@/lib/stellar";
import { getActiveNotes, markNoteSpent, type ShieldedNote } from "@/lib/notes";
import * as StellarSdk from "@stellar/stellar-sdk";

export default function WithdrawPage() {
  const { address, signTransaction } = useWallet();
  const [status, setStatus] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [selectedNote, setSelectedNote] = useState<ShieldedNote | null>(null);
  const [proofHex, setProofHex] = useState("");
  const [publicInputsHex, setPublicInputsHex] = useState("");

  const activeNotes = typeof window !== "undefined" ? getActiveNotes() : [];

  async function handleWithdraw() {
    if (!address || !selectedNote) return;
    if (!proofHex || !publicInputsHex) {
      setStatus("Error: Paste the proof and public inputs generated by the prover.");
      return;
    }

    setIsLoading(true);
    setStatus("Building withdraw transaction...");

    try {
      const publicInputsScVal = StellarSdk.xdr.ScVal.scvBytes(
        Buffer.from(publicInputsHex.replace(/^0x/, ""), "hex"),
      );
      const proofScVal = StellarSdk.xdr.ScVal.scvBytes(
        Buffer.from(proofHex.replace(/^0x/, ""), "hex"),
      );

      const tx = await buildContractCall(
        POOL_CONTRACT_ID,
        "withdraw",
        [publicInputsScVal, proofScVal],
        address,
      );

      setStatus("Waiting for wallet signature...");
      const signedXdr = await signTransaction(tx.toXDR());

      setStatus("Submitting transaction...");
      const txHash = await submitTransaction(signedXdr);

      markNoteSpent(selectedNote.commitment);
      setSelectedNote(null);
      setProofHex("");
      setPublicInputsHex("");
      setStatus(`Withdrawal successful! TX: ${txHash.slice(0, 12)}...`);
    } catch (err) {
      setStatus(`Error: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setIsLoading(false);
    }
  }

  if (!address) {
    return (
      <div className="mx-auto max-w-2xl px-6 py-16">
        <h1 className="text-2xl font-bold">Withdraw</h1>
        <div className="mt-6 rounded-xl border border-zinc-800 bg-zinc-900 p-8 text-center">
          <p className="text-zinc-400">Connect your wallet to withdraw.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1 className="text-2xl font-bold">Withdraw from Shielded Pool</h1>
      <p className="mt-2 text-sm text-zinc-400">
        Prove you own a note in the Merkle tree without revealing which one.
        Generate the ZK proof off-chain, then submit it here.
      </p>

      <div className="mt-8 space-y-6">
        {/* Note selector */}
        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-6">
          <h3 className="text-sm font-medium text-zinc-400">
            Select a Note ({activeNotes.length} available)
          </h3>
          {activeNotes.length === 0 ? (
            <p className="mt-3 text-sm text-zinc-500">
              No active notes. Deposit funds first.
            </p>
          ) : (
            <div className="mt-3 space-y-2">
              {activeNotes.map((note) => (
                <button
                  key={note.commitment}
                  onClick={() => setSelectedNote(note)}
                  className={`w-full rounded-lg border p-3 text-left text-sm transition-colors ${
                    selectedNote?.commitment === note.commitment
                      ? "border-white bg-zinc-800"
                      : "border-zinc-800 hover:border-zinc-700"
                  }`}
                >
                  <div className="font-mono text-xs text-zinc-300">
                    {note.commitment.slice(0, 16)}...{note.commitment.slice(-16)}
                  </div>
                  <div className="mt-1 text-xs text-zinc-500">
                    Created {new Date(note.createdAt).toLocaleDateString()}
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>

        {selectedNote && (
          <>
            {/* Note details */}
            <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-6">
              <h3 className="mb-3 text-sm font-medium text-zinc-400">
                Note Details
              </h3>
              <div className="space-y-2 text-xs font-mono">
                <div>
                  <span className="text-zinc-500">Nullifier: </span>
                  <span className="text-zinc-300 break-all">
                    {selectedNote.nullifier}
                  </span>
                </div>
                <div>
                  <span className="text-zinc-500">Secret: </span>
                  <span className="text-zinc-300 break-all">
                    {selectedNote.secret}
                  </span>
                </div>
                <div>
                  <span className="text-zinc-500">Leaf Index: </span>
                  <span className="text-zinc-300">
                    {selectedNote.leafIndex}
                  </span>
                </div>
              </div>
              <p className="mt-4 text-xs text-zinc-500">
                Use these values with{" "}
                <code className="rounded bg-zinc-800 px-1">just prove-pool</code>{" "}
                to generate the ZK proof off-chain.
              </p>
            </div>

            {/* Proof input */}
            <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-6">
              <h3 className="mb-3 text-sm font-medium text-zinc-400">
                Proof Data
              </h3>
              <div className="space-y-4">
                <div>
                  <label className="mb-1 block text-xs text-zinc-500">
                    Public Inputs (hex)
                  </label>
                  <textarea
                    value={publicInputsHex}
                    onChange={(e) => setPublicInputsHex(e.target.value.trim())}
                    placeholder="Paste public_inputs hex from prover output..."
                    rows={3}
                    className="w-full rounded-lg border border-zinc-700 bg-zinc-800 p-3 font-mono text-xs text-zinc-300 placeholder-zinc-600 focus:border-zinc-500 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="mb-1 block text-xs text-zinc-500">
                    Proof (hex)
                  </label>
                  <textarea
                    value={proofHex}
                    onChange={(e) => setProofHex(e.target.value.trim())}
                    placeholder="Paste proof hex from prover output..."
                    rows={3}
                    className="w-full rounded-lg border border-zinc-700 bg-zinc-800 p-3 font-mono text-xs text-zinc-300 placeholder-zinc-600 focus:border-zinc-500 focus:outline-none"
                  />
                </div>
              </div>
            </div>

            <button
              onClick={handleWithdraw}
              disabled={isLoading || !proofHex || !publicInputsHex}
              className="w-full rounded-lg bg-white py-3 text-sm font-semibold text-black transition-colors hover:bg-zinc-200 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {isLoading ? "Processing..." : "Submit Withdrawal Proof"}
            </button>
          </>
        )}

        {status && (
          <div
            className={`rounded-lg p-3 text-sm ${
              status.startsWith("Error")
                ? "bg-red-900/30 text-red-400"
                : status.includes("successful")
                  ? "bg-green-900/30 text-green-400"
                  : "bg-zinc-800 text-zinc-300"
            }`}
          >
            {status}
          </div>
        )}
      </div>
    </div>
  );
}
